apiVersion: v1
kind: Secret
metadata:
  name: minio-image-source-secret
  namespace: serverless
type: Opaque
data:
  MINIO_SERVER: cGxheS5taW4uaW8=
  MINIO_BUCKET: aW1hZ2UtcHJvY2Vzc2luZw==
  MINIO_KEY: UTNBTTNVUTg2N1NQUVFBNDNQMkY=
  MINIO_SECRET: enVmK3RmdGVTbHN3UnU3Qko4Nndla2l0bmlmSUxiWmFtMUtZWTNURw==
